apiVersion: apps/v1
kind: Deployment
metadata:
  name: week-9-tcc231003-prod
spec:
  selector:
    matchLabels:
      app: week-9-tcc231003-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: week-9-tcc231003-prod
    spec:
      containers:
        - name: application
          image: steps.retag.outputs.IMAGE_TOCHANGE
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TZ
              value: Asia/Bangkok
          ports:
            - containerPort: 80
