apiVersion: v1
kind: Service
metadata:
  name: week-9-tcc231003-prod
  labels:
    app: week-9-tcc231003-prod
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: week-9-tcc231003-prod
