name: "develop"

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  # analyze:
  #   name: Analyze CodeQL
  #   runs-on: self-hosted
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write

  #   defaults:
  #     run:
  #       working-directory: ./application/sample_csharp

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: ["csharp"]

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v2
  #       with:
  #         languages: ${{ matrix.language }}

  #     - name: Autobuild
  #       uses: github/codeql-action/autobuild@v2

  #     - name: Perform CodeQL Analysis
  #       uses: github/codeql-action/analyze@v2
  #       with:
  #         category: "/language:${{matrix.language}}"

  #     - name: Save CodeQL results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: codeql-results
  #         path: ./codeql-results

  containerize:
    name: Build & Push Docker Image
    runs-on: self-hosted

    # needs: analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.APP_IMAGE }}
          tags: ${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./application/sample_csharp
          file: ./application/sample_csharp/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy-to-develop:
    needs: containerize
    runs-on: self-hosted
    environment: develop

    defaults:
      run:
        working-directory: ./manifest/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kube Config
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          mkdir -p $HOME/.kube
          mv kubeconfig $HOME/.kube/config

      - name: Set KUBE_CONTEXT
        run: |
          kubectl config use-context "${{ secrets.KUBE_CONTEXT }}"

      - name: Update Deployment to k8s
        run: |
          export APP_IMAGE_URL=${{ vars.APP_IMAGE }}:${{ github.sha }}
          yq -i '.spec.template.spec.containers[0].image = strenv("${{ env.APP_IMAGE_URL }}")' deployment.yaml
          kubectl apply -f deployment.yaml -n ${{ secrets.KUBE_NAMESPACE }}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add deployment.yaml
          git commit -m "bot: update deployment ${{ github.sha }}"
          git push
