name: "production"

on:
  push:
    branches:
      - main
  workflow_dispatch:

# on:
#   pull_request:
#     branches:
#       - main
jobs:
  retag-container:
    name: Retag Container Image
    runs-on: self-hosted
    environment: production

    outputs:
      id: retag
      IMAGE_TOCHANGE: ${{ steps.retag.outputs.IMAGE_TOCHANGE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub or your container registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Retag Container Image
        id: retag
        working-directory: ./manifest/dev
        run: |
          IMAGE_SOURCE=$(yq eval '.spec.template.spec.containers[0].image' deployment.yaml)
          docker pull $IMAGE_SOURCE

          IMAGE_TOCHANGE=${{ secrets.APP_IMAGE }}:$GITHUB_RUN_NUMBER

          docker tag $IMAGE_SOURCE $IMAGE_TOCHANGE
          docker push $IMAGE_TOCHANGE
          echo "IMAGE_TOCHANGE=$IMAGE_TOCHANGE" >> $GITHUB_ENV
          echo "::set-env name=IMAGE_TOCHANGE::$IMAGE_TOCHANGE"

      - name: Debug - Print IMAGE_TOCHANGE in retag-container
        run: |
          echo "DEBUG: IMAGE_TOCHANGE=$IMAGE_TOCHANGE"
